import type { ImageSourcePropType } from "react-native";

import type { QuizQuestion } from "@/features/quiz/data";

export const ltoReviewerQuestions = [
  {
    id: "lto-reviewer-001",
    prompt: "While driving, you should look at your side and rear view mirror:",
    answerId: "choice-a",
    explanation: "Correct answer: Quickly.",
    choices: [
      { id: "choice-a", label: "Quickly" },
      { id: "choice-b", label: "If you want" },
      { id: "choice-c", label: "Not less than once per one minute" },
    ],
  },
  {
    id: "lto-reviewer-002",
    prompt: "You can overtake in the right side of your vehicle if:",
    answerId: "choice-a",
    explanation: "Correct answer: The road has two or more lanes going in one direction.",
    choices: [
      { id: "choice-a", label: "The road has two or more lanes going in one direction" },
      { id: "choice-b", label: "The road is two-way" },
      { id: "choice-c", label: "The sidewalk is wide" },
    ],
  },
  {
    id: "lto-reviewer-003",
    prompt: "A person who drives while under influence of alcohol or drugs is punishable by law with:",
    answerId: "choice-c",
    explanation: "Correct answer: All answers are correct.",
    choices: [
      { id: "choice-a", label: "Suspension of license" },
      { id: "choice-b", label: "Fines and imprisonment" },
      { id: "choice-c", label: "All answers are correct" },
    ],
  },
  {
    id: "lto-reviewer-004",
    prompt: "Before leaving the parking area, you should:",
    answerId: "choice-a",
    explanation: "Correct answer: Look around first.",
    choices: [
      { id: "choice-a", label: "Look around first" },
      { id: "choice-b", label: "Sound your horn" },
      { id: "choice-c", label: "Immediately go" },
    ],
  },
  {
    id: "lto-reviewer-005",
    prompt: "The minimum age in the application for Non-Professional Driver's License is:",
    answerId: "choice-c",
    explanation: "Correct answer: 17 years old.",
    choices: [
      { id: "choice-a", label: "18 years old" },
      { id: "choice-b", label: "16 years old" },
      { id: "choice-c", label: "17 years old" },
    ],
  },
  {
    id: "lto-reviewer-006",
    prompt: "After overtaking, you want to safely go back to the lane where you where you came from, you should:",
    answerId: "choice-a",
    explanation: "Correct answer: Use the rear view mirror to check the vehicle you have overtaken.",
    choices: [
      { id: "choice-a", label: "Use the rear view mirror to check the vehicle you have overtaken" },
      { id: "choice-b", label: "Look at the vehicle you have overtaken by turning your head" },
      { id: "choice-c", label: "Stop" },
    ],
  },
  {
    id: "lto-reviewer-007",
    prompt: "In an intersection with a STOP sign, you should:",
    answerId: "choice-b",
    explanation: "Correct answer: Stop and proceed if there is no danger.",
    choices: [
      { id: "choice-a", label: "Slow down and proceed if there is no danger" },
      { id: "choice-b", label: "Stop and proceed if there is no danger" },
      { id: "choice-c", label: "Give way to vehicles going from left and right, proceed if there is no danger" },
    ],
  },
  {
    id: "lto-reviewer-008",
    prompt: "Obtaining a driver's license is:",
    answerId: "choice-b",
    explanation: "Correct answer: A privilege.",
    choices: [
      { id: "choice-a", label: "An honor" },
      { id: "choice-b", label: "A privilege" },
      { id: "choice-c", label: "A right" },
    ],
  },
  {
    id: "lto-reviewer-009",
    prompt: "A Non-Professional driver's license is suited for:",
    answerId: "choice-a",
    explanation: "Correct answer: Private vehicles.",
    choices: [
      { id: "choice-a", label: "Private vehicles" },
      { id: "choice-b", label: "Public utility vehicles" },
      { id: "choice-c", label: "All types of vehicles" },
    ],
  },
  {
    id: "lto-reviewer-010",
    prompt: "What should you prepare for a long trip?",
    answerId: "choice-c",
    explanation: "Correct answer: All answers are correct.",
    choices: [
      { id: "choice-a", label: "Prepare the necessary tools that can be used to repair the vehicle" },
      { id: "choice-b", label: "Plan your route and make sure the vehicle is running in good condition" },
      { id: "choice-c", label: "All answers are correct" },
    ],
  },
  {
    id: "lto-reviewer-011",
    prompt: "When parking uphill and parallel to the sidewalk, you should turn the wheel:",
    answerId: "choice-b",
    explanation: "Correct answer: Away from the sidewalk curb.",
    choices: [
      { id: "choice-a", label: "To the sidewalk curb" },
      { id: "choice-b", label: "Away from the sidewalk curb" },
      { id: "choice-c", label: "Parallel with the sidewalk curb" },
    ],
  },
  {
    id: "lto-reviewer-012",
    prompt: "The vehicle is parked if:",
    answerId: "choice-c",
    explanation: "Correct answer: The vehicle is stationary with the engine turned off.",
    choices: [
      { id: "choice-a", label: "The vehicle is not moving while unloading passengers" },
      { id: "choice-b", label: "The vehicle is not moving while loading passengers" },
      { id: "choice-c", label: "The vehicle is stationary with the engine turned off" },
    ],
  },
  {
    id: "lto-reviewer-013",
    prompt: "What is the meaning of blinking red traffic light?",
    answerId: "choice-c",
    explanation: "Correct answer: Stop and proceed if there is no danger ahead.",
    choices: [
      { id: "choice-a", label: "Wait for the green signal" },
      { id: "choice-b", label: "Slow down and proceed if there is no danger ahead" },
      { id: "choice-c", label: "Stop and proceed if there is no danger ahead" },
    ],
  },
  {
    id: "lto-reviewer-014",
    prompt: "What should you do before turning left or right?",
    answerId: "choice-b",
    explanation: "Correct answer: Give signal not less than 30 meters before turning.",
    choices: [
      { id: "choice-a", label: "Immediately turn and sound your horn" },
      { id: "choice-b", label: "Give signal not less than 30 meters before turning" },
      { id: "choice-c", label: "Ignore giving a signal" },
    ],
  },
  {
    id: "lto-reviewer-015",
    prompt: "While changing lanes, you should give signal, check your rear view mirror and:",
    answerId: "choice-a",
    explanation: "Correct answer: Watch out for oncoming vehicles.",
    choices: [
      { id: "choice-a", label: "Watch out for oncoming vehicles" },
      { id: "choice-b", label: "Sound your horn" },
      { id: "choice-c", label: "Turn on the vehicle's headlight" },
    ],
  },
  {
    id: "lto-reviewer-016",
    prompt: "You can overtake in a highway if it has two lanes with:",
    answerId: "choice-b",
    explanation: "Correct answer: Broken yellow line.",
    choices: [
      { id: "choice-a", label: "Continuous white line" },
      { id: "choice-b", label: "Broken yellow line" },
      { id: "choice-c", label: "Continuous yellow line" },
    ],
  },
  {
    id: "lto-reviewer-017",
    prompt: "Not following road and traffic rules:",
    answerId: "choice-b",
    explanation: "Correct answer: May engage you in an accident.",
    choices: [
      { id: "choice-a", label: "Proves that you are a good driver" },
      { id: "choice-b", label: "May engage you in an accident" },
      { id: "choice-c", label: "Saves fuel" },
    ],
  },
  {
    id: "lto-reviewer-018",
    prompt: "It is more dangerous to turn left than to turn right because:",
    answerId: "choice-b",
    explanation: "Correct answer: You have to be aware and cautious from vehicles coming from left or right sides of the road.",
    choices: [
      { id: "choice-a", label: "Vehicles coming from left is faster" },
      { id: "choice-b", label: "You have to be aware and cautious from vehicles coming from left or right sides of the road" },
      { id: "choice-c", label: "The road has more lanes" },
    ],
  },
  {
    id: "lto-reviewer-019",
    prompt: "The safest response even if you have rights on the road is:",
    answerId: "choice-a",
    explanation: "Correct answer: Don't force your rights.",
    choices: [
      { id: "choice-a", label: "Don't force your rights" },
      { id: "choice-b", label: "Sound your horn" },
      { id: "choice-c", label: "Force your rights" },
    ],
  },
  {
    id: "lto-reviewer-020",
    prompt: "In a roundabout (rotunda), which has road rights?",
    answerId: "choice-b",
    explanation: "Correct answer: The vehicles in the roundabout.",
    choices: [
      { id: "choice-a", label: "The vehicles approaching the roundabout" },
      { id: "choice-b", label: "The vehicles in the roundabout" },
      { id: "choice-c", label: "The vehicles facing the green light" },
    ],
  },
  {
    id: "lto-reviewer-021",
    prompt: "You are not allowed to overtake at the foot bridge because:",
    answerId: "choice-b",
    explanation: "Correct answer: You cannot see oncoming vehicles.",
    choices: [
      { id: "choice-a", label: "People are crossing" },
      { id: "choice-b", label: "You cannot see oncoming vehicles" },
      { id: "choice-c", label: "The bridge is narrow" },
    ],
  },
  {
    id: "lto-reviewer-022",
    prompt: "What is the meaning of blinking yellow traffic light?",
    answerId: "choice-a",
    explanation: "Correct answer: Slow down and proceed if there is no danger.",
    choices: [
      { id: "choice-a", label: "Slow down and proceed if there is no danger" },
      { id: "choice-b", label: "Stop and wait for the traffic light to change" },
      { id: "choice-c", label: "Wait for the green light" },
    ],
  },
  {
    id: "lto-reviewer-023",
    prompt: "What is the meaning of continuous yellow line in the road?",
    answerId: "choice-b",
    explanation: "Correct answer: It is prohibited to overtake.",
    choices: [
      { id: "choice-a", label: "You are allowed to overtake" },
      { id: "choice-b", label: "It is prohibited to overtake" },
      { id: "choice-c", label: "All answers are correct" },
    ],
  },
  {
    id: "lto-reviewer-024",
    prompt: "According to the law, you are not allowed to drive fast, except when:",
    answerId: "choice-c",
    explanation: "Correct answer: All answers are correct.",
    choices: [
      { id: "choice-a", label: "There is no danger in the road" },
      { id: "choice-b", label: "Speed is in accordance with the given speed limit" },
      { id: "choice-c", label: "All answers are correct" },
    ],
  },
  {
    id: "lto-reviewer-025",
    prompt: "Having a license means you can drive:",
    answerId: "choice-b",
    explanation: "Correct answer: Vehicles allowed indicated in your license.",
    choices: [
      { id: "choice-a", label: "All types of vehicle" },
      { id: "choice-b", label: "Vehicles allowed indicated in your license" },
      { id: "choice-c", label: "Public utility vehicle only" },
    ],
  },
  {
    id: "lto-reviewer-026",
    prompt: "If a vehicle in front of you has a high beam light which is blinding your vision, what should you do?",
    answerId: "choice-b",
    explanation: "Correct answer: Do not look at glaring light, quickly look on the right side of the road.",
    choices: [
      { id: "choice-a", label: "Switch your headlight on high also" },
      { id: "choice-b", label: "Do not look at glaring light, quickly look on the right side of the road" },
      { id: "choice-c", label: "Stare at the glaring light" },
    ],
  },
  {
    id: "lto-reviewer-027",
    prompt: "If you are approaching a curve, what should you do?",
    answerId: "choice-a",
    explanation: "Correct answer: Slow down.",
    choices: [
      { id: "choice-a", label: "Slow down" },
      { id: "choice-b", label: "Speed up" },
      { id: "choice-c", label: "Abruptly push the brake" },
    ],
  },
  {
    id: "lto-reviewer-028",
    prompt: "What is the meaning of a triangle traffic sign with red border color?",
    answerId: "choice-b",
    explanation: "Correct answer: Warning sign.",
    choices: [
      { id: "choice-a", label: "Reminder sign" },
      { id: "choice-b", label: "Warning sign" },
      { id: "choice-c", label: "Information sign" },
    ],
  },
  {
    id: "lto-reviewer-029",
    prompt: "What is the meaning of a square or rectangle traffic sign with blue and white color?",
    answerId: "choice-c",
    explanation: "Correct answer: Information sign.",
    choices: [
      { id: "choice-a", label: "Giving direction" },
      { id: "choice-b", label: "Warning sign" },
      { id: "choice-c", label: "Information sign" },
    ],
  },
  {
    id: "lto-reviewer-030",
    prompt: "What is the meaning of a circle, octagon or inverted triangle traffic sign with red border color?",
    answerId: "choice-a",
    explanation: "Correct answer: Regulatory sign.",
    choices: [
      { id: "choice-a", label: "Regulatory sign" },
      { id: "choice-b", label: "Warning sign" },
      { id: "choice-c", label: "Giving direction" },
    ],
  },
  {
    id: "lto-reviewer-031",
    prompt: "What is the meaning of green traffic light?",
    answerId: "choice-a",
    explanation: "Correct answer: Signal to start the vehicle moving.",
    choices: [
      { id: "choice-a", label: "Go signal for the vehicle" },
      { id: "choice-b", label: "Stop at the given line" },
      { id: "choice-c", label: "You are allowed to proceed by slowing down" },
    ],
  },
  {
    id: "lto-reviewer-032",
    prompt: "What is the meaning of blinking red traffic light?",
    answerId: "choice-b",
    explanation: "Correct answer: Stop for a while and continue if there is no danger.",
    choices: [
      { id: "choice-a", label: "Stop at the given line" },
      { id: "choice-b", label: "Stop for a while and continue if there is no danger" },
      { id: "choice-c", label: "Drive faster" },
    ],
  },
  {
    id: "lto-reviewer-033",
    prompt: "What is the meaning of yellow traffic light?",
    answerId: "choice-b",
    explanation: "Correct answer: Prepare to stop, red traffic light is about to light up.",
    choices: [
      { id: "choice-a", label: "Stop" },
      { id: "choice-b", label: "Prepare to stop, red traffic light is about to light up" },
      { id: "choice-c", label: "You can go, but slow down" },
    ],
  },
  {
    id: "lto-reviewer-034",
    prompt: "What is the meaning of green traffic light?",
    answerId: "choice-a",
    explanation: "Correct answer: The vehicle should not stop.",
    choices: [
      { id: "choice-a", label: "The vehicle should not stop" },
      { id: "choice-b", label: "The vehicle should stop" },
      { id: "choice-c", label: "The vehicle should slow down" },
    ],
  },
  {
    id: "lto-reviewer-035",
    prompt: "What is the meaning of green arrow traffic light?",
    answerId: "choice-b",
    explanation: "Correct answer: Allowing vehicles to go right or left.",
    choices: [
      { id: "choice-a", label: "It is prohibited to enter on the direction of the arrow" },
      { id: "choice-b", label: "Allowing vehicles to go right or left" },
      { id: "choice-c", label: "Pedestrians can cross" },
    ],
  },
  {
    id: "lto-reviewer-036",
    prompt: "What is the meaning of yellow arrow traffic light?",
    answerId: "choice-b",
    explanation: "Correct answer: The red arrow traffic light is about to light up.",
    choices: [
      { id: "choice-a", label: "Giving signal for right or left direction" },
      { id: "choice-b", label: "The red arrow traffic light is about to light up" },
      { id: "choice-c", label: "Allowing vehicles to go left, right or straight" },
    ],
  },
  {
    id: "lto-reviewer-037",
    prompt: "What are white lines in the road for?",
    answerId: "choice-b",
    explanation: "Correct answer: Separates traffic going in one direction.",
    choices: [
      { id: "choice-a", label: "Divides lanes going in one direction" },
      { id: "choice-b", label: "Separates traffic going in one direction" },
      { id: "choice-c", label: "Sign that you can go left or right" },
    ],
  },
  {
    id: "lto-reviewer-038",
    prompt: "Broken yellow line on the road means:",
    answerId: "choice-c",
    explanation: "Correct answer: You are allowed to overtake on the left side.",
    choices: [
      { id: "choice-a", label: "You are allowed to overtake on the right side" },
      { id: "choice-b", label: "It is prohibited to overtake on the left or right side" },
      { id: "choice-c", label: "You are allowed to overtake on the left side" },
    ],
  },
  {
    id: "lto-reviewer-039",
    prompt: "Broken white line on the road means:",
    answerId: "choice-a",
    explanation: "Correct answer: You are allowed to overtake on left or right side if there is no danger.",
    choices: [
      { id: "choice-a", label: "You are allowed to overtake on left or right side if there is no danger" },
      { id: "choice-b", label: "It is prohibited to overtake on the left side" },
      { id: "choice-c", label: "It is prohibited to overtake on the right side" },
    ],
  },
  {
    id: "lto-reviewer-040",
    prompt: "When should a driver make a decision?",
    answerId: "choice-c",
    explanation: "Correct answer: While driving to anticipate other driver's actions.",
    choices: [
      { id: "choice-a", label: "If there is a heavy traffic" },
      { id: "choice-b", label: "If he is a good driver" },
      { id: "choice-c", label: "While driving to anticipate other driver's actions" },
    ],
  },
  {
    id: "lto-reviewer-041",
    prompt: "A continuous parallel double yellow line on the road means:",
    answerId: "choice-b",
    explanation: "Correct answer: It is dangerous to overtake.",
    choices: [
      { id: "choice-a", label: "You are allowed to overtake on the right side" },
      { id: "choice-b", label: "It is dangerous to overtake" },
      { id: "choice-c", label: "You are allowed to overtake on the left side" },
    ],
  },
  {
    id: "lto-reviewer-042",
    prompt: "If the driver of a vehicle in front of you is giving a hand signal by pointing his left hand upwards, he will surely:",
    answerId: "choice-b",
    explanation: "Correct answer: Turn right.",
    choices: [
      { id: "choice-a", label: "Turn left" },
      { id: "choice-b", label: "Turn right" },
      { id: "choice-c", label: "Stop" },
    ],
  },
  {
    id: "lto-reviewer-043",
    prompt: "A driver should give a signal when turning left or right on the road intersection in no less than:",
    answerId: "choice-c",
    explanation: "Correct answer: 30 meters.",
    choices: [
      { id: "choice-a", label: "15 meters" },
      { id: "choice-b", label: "60 meters" },
      { id: "choice-c", label: "30 meters" },
    ],
  },
  {
    id: "lto-reviewer-044",
    prompt: "Before changing lanes on a highway, you must give a signal for:",
    answerId: "choice-a",
    explanation: "Correct answer: Ten seconds before doing it.",
    choices: [
      { id: "choice-a", label: "Ten seconds before doing it" },
      { id: "choice-b", label: "Five minutes before doing it" },
      { id: "choice-c", label: "One minute before doing it" },
    ],
  },
  {
    id: "lto-reviewer-045",
    prompt: "When riding a motorcycle and you would like to turn right, you should signal with:",
    answerId: "choice-a",
    explanation: "Correct answer: Your left hand pointing upward.",
    choices: [
      { id: "choice-a", label: "Your left hand pointing upward" },
      { id: "choice-b", label: "Your right hand pointing to the right" },
      { id: "choice-c", label: "Your right hand pointing upward" },
    ],
  },
  {
    id: "lto-reviewer-046",
    prompt: "The necessary distance in between you and a vehicle you are following should be:",
    answerId: "choice-b",
    explanation: "Correct answer: The same length as a full vehicle.",
    choices: [
      { id: "choice-a", label: "The same length as three full vehicles" },
      { id: "choice-b", label: "The same length as a full vehicle" },
      { id: "choice-c", label: "The same length as two full vehicles" },
    ],
  },
  {
    id: "lto-reviewer-047",
    prompt: "Which place you should not overtake?",
    answerId: "choice-c",
    explanation: "Correct answer: All answers are correct.",
    choices: [
      { id: "choice-a", label: "In an intersection" },
      { id: "choice-b", label: "At the foot of the bridge" },
      { id: "choice-c", label: "All answers are correct" },
    ],
  },
  {
    id: "lto-reviewer-048",
    prompt: "Driving with a fake license is prohibited and punishable by:",
    answerId: "choice-a",
    explanation: "Correct answer: Php 1,500.00 and six months suspension in obtaining a license.",
    choices: [
      { id: "choice-a", label: "Php 1,500.00 and six months suspension in obtaining a license" },
      { id: "choice-b", label: "Not more than six months imprisonment" },
      { id: "choice-c", label: "Php 300.00" },
    ],
  },
  {
    id: "lto-reviewer-049",
    prompt: "What should you do if a policeman stops you?",
    answerId: "choice-a",
    explanation: "Correct answer: Stop and give the license and other papers for the vehicle if the policeman asks for it..",
    choices: [
      { id: "choice-a", label: "Stop and give the license and other papers for the vehicle if the policeman asks for it." },
      { id: "choice-b", label: "Don't mind the cop and drive faster." },
      { id: "choice-c", label: "Stop and argue with the policeman." },
    ],
  },
  {
    id: "lto-reviewer-050",
    prompt: "Double broken yellow line in the road means:",
    answerId: "choice-b",
    explanation: "Correct answer: You are allowed to overtake on the left or right side of the road if there is no danger.",
    choices: [
      { id: "choice-a", label: "It is prohibited to overtake on the left side" },
      { id: "choice-b", label: "You are allowed to overtake on the left or right side if there is no danger" },
      { id: "choice-c", label: "It is prohibited to overtake on the right side" },
    ],
  },
  {
    id: "lto-reviewer-051",
    prompt: "If the driver of the vehicle in front of you is stretching his left arm out and gives you a hand signal pointing to the left, he will:",
    answerId: "choice-c",
    explanation: "Correct answer: Turn left.",
    choices: [
      { id: "choice-a", label: "Turn right" },
      { id: "choice-b", label: "Stop" },
      { id: "choice-c", label: "Turn left" },
    ],
  },
  {
    id: "lto-reviewer-052",
    prompt: "If the brake light of the vehicle in front of you lights up, you should:",
    answerId: "choice-b",
    explanation: "Correct answer: Prepare to push the brake.",
    choices: [
      { id: "choice-a", label: "Depress the horn" },
      { id: "choice-b", label: "Prepare to push the brake" },
      { id: "choice-c", label: "Turn right or left" },
    ],
  },
  {
    id: "lto-reviewer-053",
    prompt: "The vehicle horn is used for:",
    answerId: "choice-c",
    explanation: "Correct answer: Giving warning to avoid accident.",
    choices: [
      { id: "choice-a", label: "Creating noise" },
      { id: "choice-b", label: "Making beautiful sounds" },
      { id: "choice-c", label: "Giving warning to avoid accident" },
    ],
  },
  {
    id: "lto-reviewer-054",
    prompt: "If you are involved in an accident, you should inform the nearest police station:",
    answerId: "choice-b",
    explanation: "Correct answer: Immediately.",
    choices: [
      { id: "choice-a", label: "Within 72 hours" },
      { id: "choice-b", label: "Immediately" },
      { id: "choice-c", label: "Within 48 hours" },
    ],
  },
  {
    id: "lto-reviewer-055",
    prompt: "The minimum age for the applicant of Professional Driver's License is:",
    answerId: "choice-a",
    explanation: "Correct answer: 18 years old.",
    choices: [
      { id: "choice-a", label: "18 years old" },
      { id: "choice-b", label: "17 years old" },
      { id: "choice-c", label: "21 years old" },
    ],
  },
  {
    id: "lto-reviewer-056",
    prompt: "The safest speed of a vehicle is according to:",
    answerId: "choice-a",
    explanation: "Correct answer: Road and weather conditions.",
    choices: [
      { id: "choice-a", label: "Road and weather conditions" },
      { id: "choice-b", label: "Condition of the vehicle" },
      { id: "choice-c", label: "Capability of the driver" },
    ],
  },
  {
    id: "lto-reviewer-057",
    prompt: "What should you do to combat fatigue and sleepiness during long road trip?",
    answerId: "choice-b",
    explanation: "Correct answer: Stop every once in a while and rest.",
    choices: [
      { id: "choice-a", label: "Drink alcohol before driving" },
      { id: "choice-b", label: "Stop every once in a while and rest" },
      { id: "choice-c", label: "Drink medicine that prevents sleepiness" },
    ],
  },
  {
    id: "lto-reviewer-058",
    prompt: "A driver is considered a Professional driver if:",
    answerId: "choice-b",
    explanation: "Correct answer: He/she is paid or earns money while driving a private or public vehicle.",
    choices: [
      { id: "choice-a", label: "He/she can drive any vehicle" },
      { id: "choice-b", label: "He/she is paid or earns money while driving a private or public vehicle" },
      { id: "choice-c", label: "He/she is a driving expert" },
    ],
  },
  {
    id: "lto-reviewer-059",
    prompt: "There are two incoming vehicles on both sides of the street of an intersection with no traffic light, which vehicle should give way?",
    answerId: "choice-c",
    explanation: "Correct answer: The last one to arrive.",
    choices: [
      { id: "choice-a", label: "The first one to arrive" },
      { id: "choice-b", label: "The first one to slow down" },
      { id: "choice-c", label: "The last one to arrive" },
    ],
  },
  {
    id: "lto-reviewer-060",
    prompt: "If the driver of a vehicle in front of you is giving a hand signal and is pointing his hand to the ground, he is:",
    answerId: "choice-a",
    explanation: "Correct answer: Stopping.",
    choices: [
      { id: "choice-a", label: "Stopping" },
      { id: "choice-b", label: "Turning right" },
      { id: "choice-c", label: "Turning left" },
    ],
  },
  {
    id: "lto-reviewer-061",
    prompt: "If you are caught due to a violation, how many days are given for you to settle your case and get your license back?",
    answerId: "choice-b",
    explanation: "Correct answer: 15 days.",
    choices: [
      { id: "choice-a", label: "30 days" },
      { id: "choice-b", label: "15 days" },
      { id: "choice-c", label: "10 days" },
    ],
  },
  {
    id: "lto-reviewer-062",
    prompt: "What is the maximum speed of a vehicle entering a school zone?",
    answerId: "choice-b",
    explanation: "Correct answer: 20 kph.",
    choices: [
      { id: "choice-a", label: "35 kph" },
      { id: "choice-b", label: "20 kph" },
      { id: "choice-c", label: "30 kph" },
    ],
  },
  {
    id: "lto-reviewer-063",
    prompt: "In which place you are prohibited to park?",
    answerId: "choice-a",
    explanation: "Correct answer: In a pedestrian crossing.",
    choices: [
      { id: "choice-a", label: "In a pedestrian crossing" },
      { id: "choice-b", label: "In a given parking space" },
      { id: "choice-c", label: "In a certain place you want to go" },
    ],
  },
  {
    id: "lto-reviewer-064",
    prompt: "If you want to drive slower than other vehicles on a highway you should stay on the:",
    answerId: "choice-a",
    explanation: "Correct answer: Right lane.",
    choices: [
      { id: "choice-a", label: "Right lane" },
      { id: "choice-b", label: "Left lane" },
      { id: "choice-c", label: "Middle lane" },
    ],
  },
  {
    id: "lto-reviewer-065",
    prompt: "What should a driver take action if his/her driver's license was lost?",
    answerId: "choice-c",
    explanation: "Correct answer: File an affidavit of loss and apply for a duplicate license.",
    choices: [
      { id: "choice-a", label: "Apply for a duplicate license" },
      { id: "choice-b", label: "Apply for a new license" },
      { id: "choice-c", label: "File an affidavit of loss and apply for a duplicate license" },
    ],
  },
  {
    id: "lto-reviewer-066",
    prompt: "A continuous single yellow line on the road means:",
    answerId: "choice-c",
    explanation: "Correct answer: It is prohibited to overtake on the left side.",
    choices: [
      { id: "choice-a", label: "You can overtake on the left or right side" },
      { id: "choice-b", label: "It is prohibited to overtake on the right side" },
      { id: "choice-c", label: "It is prohibited to overtake on the left side" },
    ],
  },
  {
    id: "lto-reviewer-067",
    prompt: "A red flag or red light should be attached to any vehicle cargo that exceeds:",
    answerId: "choice-a",
    explanation: "Correct answer: One meter from the back of the car.",
    choices: [
      { id: "choice-a", label: "One meter from the back of the car" },
      { id: "choice-b", label: "Three meters from the back of the car" },
      { id: "choice-c", label: "Two meters from the back of the car" },
    ],
  },
  {
    id: "lto-reviewer-068",
    prompt: "What should you bring before driving a vehicle?",
    answerId: "choice-a",
    explanation: "Correct answer: Driver's license, vehicle registration, and receipt of last LTO payment for the vehicle.",
    choices: [
      { id: "choice-a", label: "Driver's license, vehicle registration, and receipt of last LTO payment for the vehicle" },
      { id: "choice-b", label: "Driver's license" },
      { id: "choice-c", label: "Driver's license and vehicle insurance paper" },
    ],
  },
  {
    id: "lto-reviewer-069",
    prompt: "If you are going to drive slow on expressway, you should move on the:",
    answerId: "choice-b",
    explanation: "Correct answer: Right lane.",
    choices: [
      { id: "choice-a", label: "Middle lane" },
      { id: "choice-b", label: "Right lane" },
      { id: "choice-c", label: "Left lane" },
    ],
  },
  {
    id: "lto-reviewer-070",
    prompt: "What should you do if the vehicle behind you wants to overtake your vehicle?",
    answerId: "choice-b",
    explanation: "Correct answer: Slow down, stay on the right, and let it overtake.",
    choices: [
      { id: "choice-a", label: "Stay on the right and stop" },
      { id: "choice-b", label: "Slow down, stay on the right, and let it overtake" },
      { id: "choice-c", label: "Sound your horn and let it pass" },
    ],
  },
  {
    id: "lto-reviewer-071",
    prompt: "You are not allowed to cross a lane with continuous yellow line on the road except if you are:",
    answerId: "choice-a",
    explanation: "Correct answer: Turning left.",
    choices: [
      { id: "choice-a", label: "Turning left" },
      { id: "choice-b", label: "Turning right" },
      { id: "choice-c", label: "Changing lanes" },
    ],
  },
  {
    id: "lto-reviewer-072",
    prompt: "Driving without license is against the law and punishable with a fine of:",
    answerId: "choice-c",
    explanation: "Correct answer: Php 1500.00.",
    choices: [
      { id: "choice-a", label: "Php 1000.00" },
      { id: "choice-b", label: "Php 1500 and the vehicle will be impounded up to 10 days" },
      { id: "choice-c", label: "Php 1500.00" },
    ],
  },
  {
    id: "lto-reviewer-073",
    prompt: "There are two incoming vehicles on the street of an intersection with no traffic light, which vehicle has the right of way?",
    answerId: "choice-a",
    explanation: "Correct answer: The vehicle from the right side.",
    choices: [
      { id: "choice-a", label: "The vehicle from the right side" },
      { id: "choice-b", label: "The vehicle that slows down first" },
      { id: "choice-c", label: "The vehicle from the left side" },
    ],
  },
  {
    id: "lto-reviewer-074",
    prompt: "What is the meaning of an arrow painted on the road?",
    answerId: "choice-a",
    explanation: "Correct answer: Follow the direction painted on the road.",
    choices: [
      { id: "choice-a", label: "Follow the direction painted on the road" },
      { id: "choice-b", label: "Slow down" },
      { id: "choice-c", label: "You are allowed to change lanes" },
    ],
  },
  {
    id: "lto-reviewer-075",
    prompt: "What should you do when an ambulance comes up behind you flashing red lights and/or sounding its siren?",
    answerId: "choice-c",
    explanation: "Correct answer: Pull over to the right and slow down or even stop if necessary.",
    choices: [
      { id: "choice-a", label: "Stop as soon as possible" },
      { id: "choice-b", label: "Speed up so that you don't hold the ambulance" },
      { id: "choice-c", label: "Pull over to the right and slow down or even stop if necessary" },
    ],
  },
  {
    id: "lto-reviewer-076",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-b",
    explanation: "Correct answer: Give Way.",
    choices: [
      { id: "choice-a", label: "No entry" },
      { id: "choice-b", label: "Give way" },
      { id: "choice-c", label: "Stop" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-076.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 76",
  },
  {
    id: "lto-reviewer-077",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-c",
    explanation: "Correct answer: Sharp turn to the left.",
    choices: [
      { id: "choice-a", label: "Priority crossroads" },
      { id: "choice-b", label: "Sharp turn to the right" },
      { id: "choice-c", label: "Sharp turn to the left" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-077.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 77",
  },
  {
    id: "lto-reviewer-078",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-b",
    explanation: "Correct answer: Priority merge on the right.",
    choices: [
      { id: "choice-a", label: "Priority side junction" },
      { id: "choice-b", label: "Priority merge on the right" },
      { id: "choice-c", label: "Priority side junction on the right" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-078.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 78",
  },
  {
    id: "lto-reviewer-079",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-b",
    explanation: "Correct answer: No blowing of horns.",
    choices: [
      { id: "choice-a", label: "No parking" },
      { id: "choice-b", label: "No blowing of horns" },
      { id: "choice-c", label: "No U-turn" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-079.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 79",
  },
  {
    id: "lto-reviewer-080",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-c",
    explanation: "Correct answer: Road narrows.",
    choices: [
      { id: "choice-a", label: "Slippery road" },
      { id: "choice-b", label: "Road widens" },
      { id: "choice-c", label: "Road narrows" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-080.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 80",
  },
  {
    id: "lto-reviewer-081",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-c",
    explanation: "Correct answer: Steep ascent.",
    choices: [
      { id: "choice-a", label: "Steep descent" },
      { id: "choice-b", label: "Steep road" },
      { id: "choice-c", label: "Steep ascent" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-081.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 81",
  },
  {
    id: "lto-reviewer-082",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-c",
    explanation: "Correct answer: Quayside or river bank.",
    choices: [
      { id: "choice-a", label: "Steep road" },
      { id: "choice-b", label: "Road under construction" },
      { id: "choice-c", label: "Quayside or river bank" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-082.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 82",
  },
  {
    id: "lto-reviewer-083",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-c",
    explanation: "Correct answer: Given speed limit.",
    choices: [
      { id: "choice-a", label: "Next intersection distance is 30 km" },
      { id: "choice-b", label: "Width restriction" },
      { id: "choice-c", label: "Given speed limit" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-083.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 83",
  },
  {
    id: "lto-reviewer-084",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-c",
    explanation: "Correct answer: Dangerous bend.",
    choices: [
      { id: "choice-a", label: "Dangerous curve to the right" },
      { id: "choice-b", label: "Dangerous curve to the left" },
      { id: "choice-c", label: "Dangerous bend" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-084.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 84",
  },
  {
    id: "lto-reviewer-085",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-b",
    explanation: "Correct answer: Stop.",
    choices: [
      { id: "choice-a", label: "No entry" },
      { id: "choice-b", label: "Stop" },
      { id: "choice-c", label: "Give way" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-085.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 85",
  },
  {
    id: "lto-reviewer-086",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-b",
    explanation: "Correct answer: Railroad crossing advance warning.",
    choices: [
      { id: "choice-a", label: "No entry for train" },
      { id: "choice-b", label: "Railroad crossing advance warning" },
      { id: "choice-c", label: "Warning intersection" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-086.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 86",
  },
  {
    id: "lto-reviewer-087",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-a",
    explanation: "Correct answer: No entry for jeepney.",
    choices: [
      { id: "choice-a", label: "No entry for jeepney" },
      { id: "choice-b", label: "No entry for bus" },
      { id: "choice-c", label: "No entry for car" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-087.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 87",
  },
  {
    id: "lto-reviewer-088",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-b",
    explanation: "Correct answer: Road under construction.",
    choices: [
      { id: "choice-a", label: "Bumpy road" },
      { id: "choice-b", label: "Road under construction" },
      { id: "choice-c", label: "Slippery road" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-088.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 88",
  },
  {
    id: "lto-reviewer-089",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-b",
    explanation: "Correct answer: School zone/Children crossing.",
    choices: [
      { id: "choice-a", label: "Railroad crossing advance warning" },
      { id: "choice-b", label: "School zone/Children crossing" },
      { id: "choice-c", label: "Hospital zone" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-089.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 89",
  },
  {
    id: "lto-reviewer-090",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-c",
    explanation: "Correct answer: No entry for power-driven vehicles drawing a trailer.",
    choices: [
      { id: "choice-a", label: "No entry for car" },
      { id: "choice-b", label: "No entry for bus" },
      { id: "choice-c", label: "No entry for power-driven vehicles drawing a trailer" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-090.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 90",
  },
  {
    id: "lto-reviewer-091",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-a",
    explanation: "Correct answer: Double turn to the left.",
    choices: [
      { id: "choice-a", label: "Double turn to the left" },
      { id: "choice-b", label: "Double turn to the right" },
      { id: "choice-c", label: "Double turn ahead" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-091.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 91",
  },
  {
    id: "lto-reviewer-092",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-c",
    explanation: "Correct answer: Animal crossing.",
    choices: [
      { id: "choice-a", label: "Animals are prohibited to cross" },
      { id: "choice-b", label: "Animal cage" },
      { id: "choice-c", label: "Animal crossing" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-092.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 92",
  },
  {
    id: "lto-reviewer-093",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-b",
    explanation: "Correct answer: Bumpy road.",
    choices: [
      { id: "choice-a", label: "Slippery road" },
      { id: "choice-b", label: "Bumpy road" },
      { id: "choice-c", label: "Steep road" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-093.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 93",
  },
  {
    id: "lto-reviewer-094",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-c",
    explanation: "Correct answer: No entry.",
    choices: [
      { id: "choice-a", label: "No left turn" },
      { id: "choice-b", label: "One-way traffic" },
      { id: "choice-c", label: "No entry" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-094.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 94",
  },
  {
    id: "lto-reviewer-095",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-a",
    explanation: "Correct answer: Priority crossroads.",
    choices: [
      { id: "choice-a", label: "Priority crossroads" },
      { id: "choice-b", label: "First aid station" },
      { id: "choice-c", label: "Railroad crossing" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-095.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 95",
  },
  {
    id: "lto-reviewer-096",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-a",
    explanation: "Correct answer: No entry for trucks.",
    choices: [
      { id: "choice-a", label: "No entry for trucks" },
      { id: "choice-b", label: "No entry for bus" },
      { id: "choice-c", label: "No entry for car" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-096.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 96",
  },
  {
    id: "lto-reviewer-097",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-b",
    explanation: "Correct answer: Do not enter if the vehicle is more than 2 meters wide.",
    choices: [
      { id: "choice-a", label: "Do not enter" },
      { id: "choice-b", label: "Do not enter if the vehicle is more than 2 meters wide" },
      { id: "choice-c", label: "Do not enter if the vehicle is 2 meters wide" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-097.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 97",
  },
  {
    id: "lto-reviewer-098",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-a",
    explanation: "Correct answer: No parking.",
    choices: [
      { id: "choice-a", label: "No parking" },
      { id: "choice-b", label: "Do not blow your horn" },
      { id: "choice-c", label: "No entry" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-098.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 98",
  },
  {
    id: "lto-reviewer-099",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-c",
    explanation: "Correct answer: Beware of falling rocks.",
    choices: [
      { id: "choice-a", label: "Road under construction" },
      { id: "choice-b", label: "Steep road" },
      { id: "choice-c", label: "Beware of falling rocks" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-099.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 99",
  },
  {
    id: "lto-reviewer-100",
    prompt: "Which answer correctly describes this road sign?",
    answerId: "choice-b",
    explanation: "Correct answer: Slippery road.",
    choices: [
      { id: "choice-a", label: "Steep road" },
      { id: "choice-b", label: "Slippery road" },
      { id: "choice-c", label: "Bumpy road" },
    ],
    image: require("../../assets/lto-reviewer/lto-reviewer-100.jpeg") as ImageSourcePropType,
    imageLabel: "LTO reviewer road sign 100",
  }
] satisfies QuizQuestion[];
